server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      #动态路由
      discovery:
        locator:
          enabled: true                  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh              #payment_route #路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service     #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**       #断言，路径相匹配的进行路由

        - id: payment_routh2              #payment_route #路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service     #匹配后提供服务的路由地址
#          filters:                           #过滤器
#            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/lb/**       #断言，路径相匹配的进行路由
#            - After=2020-04-04T00:27:56.980+08:00[Asia/Shanghai]
#            - Before=2022-04-04T00:27:56.980+08:00[Asia/Shanghai]
#            - Between=2020-04-04T00:27:56.980+08:00[Asia/Shanghai],2022-04-04T00:27:56.980+08:00[Asia/Shanghai]
#            - Cookie=username,kipp
#            - Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.study.com
#            - Method=GET
#            - Query=username, \d+  #要有参数名username并且值还是整数才能路由

      #静态路由
#      routes:
#        - id: payment_routh              #payment_route #路由的id，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8008     #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/**       #断言，路径相匹配的进行路由
#
#        - id: payment_routh2              #payment_route #路由的id，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8008     #匹配后提供服务的路由地址
#          predicates:
#              - Path=/payment/lb/**       #断言，路径相匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #表示是否将自己注册金EurekaServer默认为true
    service-url:
      register-with-eureka: true
        #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
