server:
  port: 81

spring:
  application:
    name: cloud-consumer-order
  ###注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}