server:
  port: 8777
  tomcat:
    remote-ip-header: r-forwarded-for
    protocol-header: r-forward-proto
  use-forward-headers: true
  servlet:
    context-path: /order

spring:
  application:
    name: order-service
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      enabled: true
      charset: utf-8
  freemarker:
    enabled: true
    suffix: .html
    request-context-attribute: rc
    content-type: text/html
    charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/study?useUnicode=true
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: debug
    org.springframework.web: info

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/html , application/xml , application/json
      min-request-size: 2048
    response:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8666/eureka/
  instance:
    prefer-ip-address: true
#    instance-id: ${spring.application.name:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    instance-id:  ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
